// app/c/[slug]/steps/contact-step.tsx
"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Ticket, TicketHeader, TicketPerforation } from "@/components/ui/ticket";
import { createClient } from "@/lib/supabase/client";
import { contactSchema, type ContactFormValues } from "@/lib/validations/contact";
import type { Business } from "@/lib/supabase/types";

interface ContactStepProps {
  business: Business;
  onSubmitted: (responseId: string, name: string, email: string, phone: string) => void;
}

export function ContactStep({ business, onSubmitted }: ContactStepProps) {
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<ContactFormValues>({
    resolver: zodResolver(contactSchema),
    defaultValues: { name: "", email: "", phone: "", consent: false },
  });

  const consent = watch("consent");

  async function onSubmit(values: ContactFormValues) {
    setSubmitting(true);
    setSubmitError(null);

    const supabase = createClient();
    const responseId = crypto.randomUUID();

    const { error } = await supabase.from("responses").insert({
      id: responseId,
      business_id: business.id,
      customer_name: values.name,
      customer_email: values.email || null,
      customer_phone: values.phone || null,
      consent: values.consent,
    });

    if (error) {
      setSubmitError("That didn't save. Check your connection and tap continue again.");
      setSubmitting(false);
      return;
    }

    onSubmitted(responseId, values.name, values.email ?? "", values.phone ?? "");
  }

  return (
    <Ticket edge="bottom" className="pb-3">
      <TicketHeader business={business.name} meta="1 of 2" />
      <TicketPerforation />

      <div className="px-6 pt-5 pb-4">
        <h1 className="font-display text-3xl leading-tight font-semibold tracking-tight text-balance">
          Get {business.reward_text || "a discount voucher"} for your review
        </h1>
        <p className="mt-1.5 text-sm text-muted-foreground">
          First, so {business.name} knows who to thank.
        </p>

        <form onSubmit={handleSubmit(onSubmit)} className="mt-5 flex flex-col gap-4">
          <div className="space-y-1.5">
            <Label htmlFor="name">Name</Label>
            <Input id="name" className="h-12 text-base" autoFocus {...register("name")} />
            {errors.name && <p className="text-sm text-destructive">{errors.name.message}</p>}
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="email">Email (optional)</Label>
            <Input id="email" type="email" className="h-12 text-base" {...register("email")} />
            {errors.email && <p className="text-sm text-destructive">{errors.email.message}</p>}
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="phone">WhatsApp number (optional)</Label>
            <Input id="phone" type="tel" className="h-12 text-base" {...register("phone")} />
          </div>

          <p className="text-xs leading-relaxed text-muted-foreground">
            This is so {business.name} can send you discount vouchers later, in exchange for
            testimonials like this one. Never used for marketing.
          </p>

          <div className="flex items-start gap-3 pt-1">
            <Checkbox
              id="consent"
              checked={consent}
              onCheckedChange={(checked) =>
                setValue("consent", checked === true, { shouldValidate: true })
              }
              className="mt-0.5"
            />
            <Label htmlFor="consent" className="text-sm leading-snug font-normal text-muted-foreground">
              I&apos;m happy for {business.name} to share my video and name publicly.
            </Label>
          </div>
          {errors.consent && <p className="text-sm text-destructive">{errors.consent.message}</p>}

          {submitError && <p className="text-sm text-destructive">{submitError}</p>}

          <Button type="submit" size="xl" className="mt-1 w-full" disabled={submitting}>
            {submitting ? "One sec" : "Continue"}
          </Button>
        </form>
      </div>
    </Ticket>
  );
}

// app/components/collection/ContactStep.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { contactSchema } from '@/lib/validations/contact'
import type { Business } from '@/lib/supabase/types'

const props = defineProps<{ business: Business }>()
const emit = defineEmits<{
  submitted: [responseId: string, name: string, email: string, phone: string]
}>()

const supabase = useSupabaseClient()
const submitting = ref(false)
const submitError = ref<string | null>(null)

const { defineField, handleSubmit, errors } = useForm({
  validationSchema: toTypedSchema(contactSchema),
  initialValues: { name: '', email: '', phone: '', consent: false },
})

const [name, nameAttrs] = defineField('name')
const [email, emailAttrs] = defineField('email')
const [phone, phoneAttrs] = defineField('phone')
const [consent] = defineField('consent')

const onSubmit = handleSubmit(async (formValues) => {
  submitting.value = true
  submitError.value = null

  const responseId = crypto.randomUUID()

  const { error } = await supabase.from('responses').insert({
    id: responseId,
    business_id: props.business.id,
    customer_name: formValues.name,
    customer_email: formValues.email || null,
    customer_phone: formValues.phone || null,
    consent: formValues.consent,
  })

  if (error) {
    submitError.value = "That didn't save. Check your connection and tap continue again."
    submitting.value = false
    return
  }

  emit('submitted', responseId, formValues.name, formValues.email ?? '', formValues.phone ?? '')
})
</script>

<template>
  <Ticket edge="bottom" class="pb-3">
    <TicketHeader :business="business.name" meta="1 of 2" />
    <TicketPerforation />

    <div class="px-6 pt-5 pb-4">
      <h1 class="font-display text-3xl leading-tight font-semibold tracking-tight text-balance">
        Get {{ business.reward_text || 'a discount voucher' }} for your review
      </h1>
      <p class="mt-1.5 text-sm text-muted-foreground">First, so {{ business.name }} knows who to thank.</p>

      <form class="mt-5 flex flex-col gap-4" @submit="onSubmit">
        <div class="space-y-1.5">
          <Label for="name">Name</Label>
          <Input id="name" v-model="name" v-bind="nameAttrs" class="h-12 text-base" autofocus />
          <p v-if="errors.name" class="text-sm text-destructive">{{ errors.name }}</p>
        </div>

        <div class="space-y-1.5">
          <Label for="email">Email (optional)</Label>
          <Input id="email" v-model="email" v-bind="emailAttrs" type="email" class="h-12 text-base" />
          <p v-if="errors.email" class="text-sm text-destructive">{{ errors.email }}</p>
        </div>

        <div class="space-y-1.5">
          <Label for="phone">WhatsApp number (optional)</Label>
          <Input id="phone" v-model="phone" v-bind="phoneAttrs" type="tel" class="h-12 text-base" />
        </div>

        <p class="text-xs leading-relaxed text-muted-foreground">
          This is so {{ business.name }} can send you discount vouchers later, in exchange for
          testimonials like this one. Never used for marketing.
        </p>

        <div class="flex items-start gap-3 pt-1">
          <Checkbox
            id="consent"
            :model-value="consent"
            class="mt-0.5"
            @update:model-value="(v) => (consent = v === true)"
          />
          <Label for="consent" class="text-sm leading-snug font-normal text-muted-foreground">
            I'm happy for {{ business.name }} to share my video and name publicly.
          </Label>
        </div>
        <p v-if="errors.consent" class="text-sm text-destructive">{{ errors.consent }}</p>

        <p v-if="submitError" class="text-sm text-destructive">{{ submitError }}</p>

        <Button type="submit" size="xl" class="mt-1 w-full" :disabled="submitting">
          {{ submitting ? 'One sec' : 'Continue' }}
        </Button>
      </form>
    </div>
  </Ticket>
</template>
