// app/components/dashboard/SettingsForm.vue
<script setup lang="ts">
import type { Business } from '@/lib/supabase/types';
import { businessSettingsSchema } from '@/lib/validations/business';
import { toTypedSchema } from '@vee-validate/zod';
import { useForm } from 'vee-validate';

const props = defineProps<{ business: Business }>()

const businessStore = useBusinessStore()
const supabase = useSupabaseClient()

const logoUrl = ref(props.business.logo_url ?? '')
const uploadingLogo = ref(false)
const saved = ref(false)

const { defineField, handleSubmit, errors, isSubmitting } = useForm({
  validationSchema: toTypedSchema(businessSettingsSchema),
  initialValues: {
    name: props.business.name,
    brand_color: props.business.brand_color,
    reward_text: props.business.reward_text ?? '',
    reward_code: props.business.reward_code ?? '',
    reward_terms: props.business.reward_terms ?? '',
  },
})

const [name, nameAttrs] = defineField('name')
const [brandColor, brandColorAttrs] = defineField('brand_color')
const [rewardText, rewardTextAttrs] = defineField('reward_text')
const [rewardCode, rewardCodeAttrs] = defineField('reward_code')
const [rewardTerms, rewardTermsAttrs] = defineField('reward_terms')

async function handleLogoChange(event: Event) {
  const file = (event.target as HTMLInputElement).files?.[0]
  if (!file) return

  uploadingLogo.value = true
  const ext = file.name.split('.').pop() || 'png'
  const path = `${props.business.id}/logo.${ext}`

  const { error } = await supabase.storage.from('logos').upload(path, file, { upsert: true, contentType: file.type })

  if (!error) {
    const {
      data: { publicUrl },
    } = supabase.storage.from('logos').getPublicUrl(path)
    logoUrl.value = `${publicUrl}?t=${Date.now()}`
  }
  uploadingLogo.value = false
}

const onSubmit = handleSubmit(async (values) => {
  saved.value = false
  await businessStore.update({
    name: values.name,
    brand_color: values.brand_color,
    reward_text: values.reward_text || null,
    reward_code: values.reward_code || null,
    reward_terms: values.reward_terms || null,
    logo_url: logoUrl.value || undefined,
  })
  saved.value = true
  setTimeout(() => (saved.value = false), 2500)
})
</script>

<template>
  <form class="flex max-w-2xl flex-col gap-6" @submit="onSubmit">
    <Card>
      <CardContent class="flex flex-col gap-4 px-6 py-6">
        <h2 class="text-sm font-semibold">Business profile</h2>

        <div class="flex items-center gap-4">
          <img v-if="logoUrl" :src="logoUrl" alt="Logo" class="h-16 w-16 rounded-full object-cover">
          <div v-else class="flex h-16 w-16 items-center justify-center rounded-full bg-muted text-lg font-semibold text-muted-foreground">
            {{ business.name.charAt(0).toUpperCase() }}
          </div>
          <div>
            <Label for="logo" class="cursor-pointer text-sm font-medium underline underline-offset-4">
              {{ uploadingLogo ? 'Uploading...' : 'Change logo' }}
            </Label>
            <input id="logo" type="file" accept="image/*" class="hidden" :disabled="uploadingLogo" @change="handleLogoChange">
          </div>
        </div>

        <div class="space-y-1.5">
          <Label for="name">Business name</Label>
          <Input id="name" v-model="name" v-bind="nameAttrs" />
          <p v-if="errors.name" class="text-sm text-destructive">{{ errors.name }}</p>
        </div>

        <div class="space-y-1.5">
          <Label for="brand_color">Brand color</Label>
          <div class="flex items-center gap-3">
            <input id="brand_color" v-model="brandColor" v-bind="brandColorAttrs" type="color" class="h-10 w-14 cursor-pointer rounded border">
            <span class="text-sm text-muted-foreground">Used as the accent color on your public collection page.</span>
          </div>
        </div>
      </CardContent>
    </Card>

    <Card>
      <CardContent class="flex flex-col gap-4 px-6 py-6">
        <h2 class="text-sm font-semibold">Reward</h2>

        <div class="space-y-1.5">
          <Label for="reward_text">Reward description</Label>
          <Input id="reward_text" v-model="rewardText" v-bind="rewardTextAttrs" placeholder="10% off your next visit" />
        </div>

        <div class="space-y-1.5">
          <Label for="reward_code">Reward code</Label>
          <Input id="reward_code" v-model="rewardCode" v-bind="rewardCodeAttrs" placeholder="THANKYOU10" />
        </div>

        <div class="space-y-1.5">
          <Label for="reward_terms">Terms</Label>
          <Textarea
            id="reward_terms"
            v-model="rewardTerms"
            v-bind="rewardTermsAttrs"
            rows="3"
            placeholder="Valid for 30 days. One per customer."
          />
        </div>
      </CardContent>
    </Card>

    <div class="flex items-center gap-3">
      <Button type="submit" :disabled="isSubmitting">{{ isSubmitting ? 'Saving...' : 'Save changes' }}</Button>
      <p v-if="saved" class="text-sm text-muted-foreground">Saved.</p>
    </div>
  </form>
</template>

// app/dashboard/settings/settings-form.tsx
"use client";

import { useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent } from "@/components/ui/card";
import { createClient } from "@/lib/supabase/client";
import { businessSettingsSchema, type BusinessSettingsValues } from "@/lib/validations/business";
import type { Business } from "@/lib/supabase/types";
import { updateBusiness } from "./actions";

export function SettingsForm({ business }: { business: Business }) {
  const [logoUrl, setLogoUrl] = useState(business.logo_url ?? "");
  const [uploadingLogo, setUploadingLogo] = useState(false);
  const [saved, setSaved] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<BusinessSettingsValues>({
    resolver: zodResolver(businessSettingsSchema),
    defaultValues: {
      name: business.name,
      brand_color: business.brand_color,
      reward_text: business.reward_text ?? "",
      reward_code: business.reward_code ?? "",
      reward_terms: business.reward_terms ?? "",
    },
  });

  async function handleLogoChange(file: File) {
    setUploadingLogo(true);
    const supabase = createClient();
    const ext = file.name.split(".").pop() || "png";
    const path = `${business.id}/logo.${ext}`;

    const { error } = await supabase.storage
      .from("logos")
      .upload(path, file, { upsert: true, contentType: file.type });

    if (!error) {
      const {
        data: { publicUrl },
      } = supabase.storage.from("logos").getPublicUrl(path);
      setLogoUrl(`${publicUrl}?t=${Date.now()}`);
    }
    setUploadingLogo(false);
  }

  async function onSubmit(values: BusinessSettingsValues) {
    setSaved(false);
    await updateBusiness(business.id, {
      name: values.name,
      brand_color: values.brand_color,
      reward_text: values.reward_text || null,
      reward_code: values.reward_code || null,
      reward_terms: values.reward_terms || null,
      logo_url: logoUrl || undefined,
    });
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="flex max-w-2xl flex-col gap-6">
      <Card>
        <CardContent className="flex flex-col gap-4 px-6 py-6">
          <h2 className="text-sm font-semibold">Business profile</h2>

          <div className="flex items-center gap-4">
            {logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img src={logoUrl} alt="Logo" className="h-16 w-16 rounded-full object-cover" />
            ) : (
              <div className="flex h-16 w-16 items-center justify-center rounded-full bg-muted text-lg font-semibold text-muted-foreground">
                {business.name.charAt(0).toUpperCase()}
              </div>
            )}
            <div>
              <Label htmlFor="logo" className="cursor-pointer text-sm font-medium underline underline-offset-4">
                {uploadingLogo ? "Uploading..." : "Change logo"}
              </Label>
              <input
                id="logo"
                type="file"
                accept="image/*"
                className="hidden"
                disabled={uploadingLogo}
                onChange={(e) => {
                  const file = e.target.files?.[0];
                  if (file) handleLogoChange(file);
                }}
              />
            </div>
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="name">Business name</Label>
            <Input id="name" {...register("name")} />
            {errors.name && <p className="text-sm text-destructive">{errors.name.message}</p>}
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="brand_color">Brand color</Label>
            <div className="flex items-center gap-3">
              <input
                id="brand_color"
                type="color"
                className="h-10 w-14 cursor-pointer rounded border"
                {...register("brand_color")}
              />
              <span className="text-sm text-muted-foreground">
                Used as the accent color on your public collection page.
              </span>
            </div>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardContent className="flex flex-col gap-4 px-6 py-6">
          <h2 className="text-sm font-semibold">Reward</h2>

          <div className="space-y-1.5">
            <Label htmlFor="reward_text">Reward description</Label>
            <Input id="reward_text" placeholder="10% off your next visit" {...register("reward_text")} />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="reward_code">Reward code</Label>
            <Input id="reward_code" placeholder="THANKYOU10" {...register("reward_code")} />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="reward_terms">Terms</Label>
            <Textarea
              id="reward_terms"
              rows={3}
              placeholder="Valid for 30 days. One per customer."
              {...register("reward_terms")}
            />
          </div>
        </CardContent>
      </Card>

      <div className="flex items-center gap-3">
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting ? "Saving..." : "Save changes"}
        </Button>
        {saved && <p className="text-sm text-muted-foreground">Saved.</p>}
      </div>
    </form>
  );
}
