// app/pages/login.vue
<script setup lang="ts">
import { toTypedSchema } from '@vee-validate/zod'
import { useForm } from 'vee-validate'
import { loginSchema } from '@/lib/validations/auth'

const supabase = useSupabaseClient()
const submitting = ref(false)
const formError = ref<string | null>(null)

const { defineField, handleSubmit, errors } = useForm({
  validationSchema: toTypedSchema(loginSchema),
  initialValues: { email: '', password: '' },
})

const [email, emailAttrs] = defineField('email')
const [password, passwordAttrs] = defineField('password')

const onSubmit = handleSubmit(async (values) => {
  submitting.value = true
  formError.value = null

  const { error } = await supabase.auth.signInWithPassword(values)

  if (error) {
    formError.value = error.message
    submitting.value = false
    return
  }

  await navigateTo('/dashboard')
})
</script>

<template>
  <div class="relative mx-auto flex min-h-svh w-full max-w-sm flex-col justify-center gap-6 px-6 py-10">
    <ThemeToggle class="absolute top-6 right-6" />
    <div>
      <h1 class="text-2xl font-semibold tracking-tight">Log in to Vouch</h1>
      <p class="mt-1 text-sm text-muted-foreground">Manage your testimonials and questions.</p>
    </div>

    <form class="flex flex-col gap-4" @submit="onSubmit">
      <div class="space-y-1.5">
        <Label for="email">Email</Label>
        <Input id="email" v-model="email" v-bind="emailAttrs" type="email" autofocus />
        <p v-if="errors.email" class="text-sm text-destructive">{{ errors.email }}</p>
      </div>

      <div class="space-y-1.5">
        <Label for="password">Password</Label>
        <Input id="password" v-model="password" v-bind="passwordAttrs" type="password" />
        <p v-if="errors.password" class="text-sm text-destructive">{{ errors.password }}</p>
      </div>

      <p v-if="formError" class="text-sm text-destructive">{{ formError }}</p>

      <Button type="submit" class="mt-2 h-11" :disabled="submitting">
        {{ submitting ? 'Logging in...' : 'Log in' }}
      </Button>
    </form>

    <p class="text-center text-sm text-muted-foreground">
      Don't have an account?
      <NuxtLink to="/signup" class="font-medium text-foreground underline underline-offset-4">Sign up</NuxtLink>
    </p>
  </div>
</template>

// app/login/page.tsx
"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { createClient } from "@/lib/supabase/client";
import { loginSchema, type LoginFormValues } from "@/lib/validations/auth";
import { ThemeToggle } from "@/components/theme-toggle";

export default function LoginPage() {
  const router = useRouter();
  const [submitting, setSubmitting] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: { email: "", password: "" },
  });

  async function onSubmit(values: LoginFormValues) {
    setSubmitting(true);
    setFormError(null);

    const supabase = createClient();
    const { error } = await supabase.auth.signInWithPassword(values);

    if (error) {
      setFormError(error.message);
      setSubmitting(false);
      return;
    }

    router.push("/dashboard");
    router.refresh();
  }

  return (
    <div className="relative mx-auto flex min-h-svh w-full max-w-sm flex-col justify-center gap-6 px-6 py-10">
      <ThemeToggle className="absolute top-6 right-6" />
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">Log in to Vouch</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Manage your testimonials and questions.
        </p>
      </div>

      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <div className="space-y-1.5">
          <Label htmlFor="email">Email</Label>
          <Input id="email" type="email" autoFocus {...register("email")} />
          {errors.email && <p className="text-sm text-destructive">{errors.email.message}</p>}
        </div>

        <div className="space-y-1.5">
          <Label htmlFor="password">Password</Label>
          <Input id="password" type="password" {...register("password")} />
          {errors.password && (
            <p className="text-sm text-destructive">{errors.password.message}</p>
          )}
        </div>

        {formError && <p className="text-sm text-destructive">{formError}</p>}

        <Button type="submit" className="mt-2 h-11" disabled={submitting}>
          {submitting ? "Logging in..." : "Log in"}
        </Button>
      </form>

      <p className="text-center text-sm text-muted-foreground">
        Don&apos;t have an account?{" "}
        <Link href="/signup" className="font-medium text-foreground underline underline-offset-4">
          Sign up
        </Link>
      </p>
    </div>
  );
}
